# Generated by Django 5.0.4 on 2024-04-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('finish_date', models.DateField(verbose_name='Finish date')),
                ('status', models.CharField(choices=[('Waiting', 'На рассмотрении'), ('Approved', 'Одобрено'), ('Rejected', 'Отклонено')], default='Waiting', max_length=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на отпуск',
            },
        ),
    ]
