# Generated by Django 5.0.4 on 2024-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество дней'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='finish_date',
            field=models.DateField(verbose_name='Конец отпуска'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='start_date',
            field=models.DateField(verbose_name='Начало отпуска'),
        ),
    ]
