# Generated by Django 5.0.4 on 2024-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_days',
            field=models.IntegerField(blank=True, default=28, max_length=2, null=True),
        ),
    ]
