# Generated by Django 5.0.4 on 2024-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_user_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Начальник', 'Начальник'), ('Сотрудник', 'Сотрудник')], default='Сотрудник', max_length=10, verbose_name='Должность'),
        ),
    ]
